### ISSUE TITLE
[BUG] Player will buy grenades and all weapons are removed

### ISSUE THREAD

**Issue by crashzk** [yonilerner/cs2-retakes-allocator#160]
When players go to buy grenades, the plugin simply removes all weapons, leaving them with just gloves, no knife, nothing.
```
2024-10-23 22:19:20.001 -03:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/clientes/OGP_User_Files/whmcs/8975/game/csgo/addons/counterstrikesharp/plugins/RetakesAllocator/RetakesAllocator.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at RetakesAllocator.RetakesAllocator.Load(Boolean hotReload) in /home/runner/work/cs2-retakes-allocator/cs2-retakes-allocator/RetakesAllocator/RetakesAllocator.cs:line 79
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
   ```

Config I'm using:
```
   {
  "UsableWeapons": [
    "Deagle",
    "Glock",
    "USPS",
    "HKP2000",
    "Elite",
    "Tec9",
    "P250",
    "CZ",
    "FiveSeven",
    "Revolver",	
    "Mac10",
    "MP9",
    "MP7",
    "P90",
    "AK47",
    "M4A1S",
    "M4A1",
    "GalilAR",	
    "AWP",	
    "SSG08"
  ],
  "AllowedWeaponSelectionTypes": [
    "PlayerChoice",
    "Random",
    "Default"
  ],
  "DefaultWeapons": {
    "Terrorist": {
      "FullBuyPrimary": "AK47",
      "HalfBuyPrimary": "Mac10",
      "Secondary": "Glock",
      "PistolRound": "Deagle"
    },
    "CounterTerrorist": {
      "FullBuyPrimary": "M4A1S",
      "HalfBuyPrimary": "MP9",
      "Secondary": "USPS",
      "PistolRound": "Deagle"
    }
  },
  "MaxNades": {
    "GLOBAL": {
      "Terrorist": {
        "Flashbang": 1,
        "Smoke": 1,
        "Molotov": 1,
        "HighExplosive": 1
      }
    }
  },
  "RoundTypeSelection": "Random",
  "RoundTypePercentages": {
    "Pistol": 30,
    "HalfBuy": 9,
    "FullBuy": 61
  },
  "RoundTypeRandomFixedCounts": {
    "Pistol": 7,
    "HalfBuy": 2,
    "FullBuy": 21
  },
  "RoundTypeManualOrdering": [
    {
      "Type": "Pistol",
      "Count": 7
    },
    {
      "Type": "HalfBuy",
      "Count": 2
    },
    {
      "Type": "FullBuy",
      "Count": 21
    }
  ],
  "MigrateOnStartup": true,
  "ResetStateOnGameRestart": true,
  "AllowAllocationAfterFreezeTime": true,
  "UseOnTickFeatures": true,
  "EnableRoundTypeAnnouncement": true,
  "EnableRoundTypeAnnouncementCenter": false,
  "EnableBombSiteAnnouncementCenter": true,
  "BombSiteAnnouncementCenterToCTOnly": true,
  "DisableDefaultBombPlantedCenterMessage": true,
  "ForceCloseBombSiteAnnouncementCenterOnPlant": true,
  "BombSiteAnnouncementCenterDelay": 1,
  "BombSiteAnnouncementCenterShowTimer": 4,
  "EnableBombSiteAnnouncementChat": false,
  "EnableNextRoundTypeVoting": false,
  "NumberOfExtraVipChancesForPreferredWeapon": 1,
  "AllowPreferredWeaponForEveryone": true,
  "ChanceForPreferredWeapon": 25,
  "MaxPreferredWeaponsPerTeam": {
    "Terrorist": 1,
    "CounterTerrorist": 1
  },
  "MinPlayersPerTeamForPreferredWeapon": {
    "Terrorist": 3,
    "CounterTerrorist": 3
  },
  "EnableCanAcquireHook": true,
  "LogLevel": "Information",
  "ChatMessagePluginName": "ZK Servidores™",
  "ChatMessagePluginPrefix": "[NORMAL][ [DARK_RED]ZK Servidores™ [NORMAL]] ",
  "InGameGunMenuCenterCommands": "gunsmenu,gunmenu,!gunmenu,!gunsmenu,!menugun,!menuguns,/gunmenu,/gunsmenu,/menugun,/menuguns",
  "InGameGunMenuChatCommands": "guns,!guns,/guns",
  "ZeusPreference": "Never",
  "DatabaseProvider": "Sqlite",
  "DatabaseConnectionString": "Data Source=data.db; Pooling=False"
}
```

**Comment by crashzk** [comment]
[UPDATE]

I believe it was my `MaxNades` error, testing now.
```
"MaxNades": {
    "GLOBAL": {
      "Terrorist": {
        "Flashbang": 1,
        "Smoke": 1,
        "Molotov": 1,
        "HighExplosive": 1
      }
    }
  },
```
