### ISSUE TITLE
Console Error 

### ISSUE THREAD

**Issue by NikolaJyun** [yonilerner/cs2-retakes-allocator#161]
An error occurs each time the plugin version 2.3.12 is loaded, but it doesn't seem to affect gameplay. I'm not entirely sure. The only small bug I know of in Retake is that after defusing, the player model slides (without the walking animation). The animation returns to normal in the next round, but this bug might not be related to the plugin since the plugin is used for weapon allocation.

17:37:17 [INFO] (cssharp:PluginContext) Loading plugin RetakesAllocator
17:37:18 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/cs2server/cs2retake/serverfiles/game/csgo/addons/counterstrikesharp/plugins/RetakesAllocator/RetakesAllocator.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at RetakesAllocator.RetakesAllocator.Load(Boolean hotReload) in /home/runner/work/cs2-retakes-allocator/cs2-retakes-allocator/RetakesAllocator/RetakesAllocator.cs:line 79
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1314
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Oct  3 2024 15:12:54
    Built from: https://github.com/alliedmodders/metamod-source/commit/557121c
    Build ID: 1314:557121c
    http://www.metamodsource.net/
css
  CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
  Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.
  See ACKNOWLEDGEMENTS.md for more information.
  Current API Version: v284 (1.0.284+5c9d38b)

Could you also improve the pistol round? Currently, only USP/Glock has armor (without a helmet), while other pistols do not.

**Comment by krydderr** [comment]
delete whole plugin and re install. had same problem, needed to generate new config file, clean install = fixed

**Comment by yonilerner** [comment]
Thanks for helping out on this issue! Closing since it seems solved
