### ISSUE TITLE
latest plugin version error during loading

### ISSUE THREAD

**Issue by LelieL91** [yonilerner/cs2-retakes-allocator#169]
Tried to upgrade from 2.3.15 to 2.3.16 and got this issue, so I also tried to do a fresh install but still.
I tried reverting to 2.3.15 and still can't load the plugin.
Current versions: MM=2.0.0-dev+1315, CSS=290
I'll send the related console log below:

```
17:14:16 [INFO] (cssharp:PluginContext) Loading plugin RetakesAllocator
17:14:18 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/RetakesAllocator/RetakesAllocator.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at RetakesAllocator.RetakesAllocator.Load(Boolean hotReload) in /home/runner/work/cs2-retakes-allocator/cs2-retakes-allocator/RetakesAllocator/RetakesAllocator.cs:line 79
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
17:14:18 [INFO] (cssharp:PluginContext) Loading plugin RetakesPlugin
17:14:18 [INFO] (cssharp:PluginContext) Finished loading plugin Retakes Plugin
```

**Comment by yonilerner** [comment]
Is the plugin working? Ive seen this error before but the plugin works fine anyway

**Comment by LelieL91** [comment]
It was the 1st time for me, now I updated to the latest version and the plugin seems correctly loaded
Thank you for your work
